version: '3.7'
services:
  blog:
    container_name: blog
    image: blog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
