# Generated by Django 4.1.2 on 2022-10-28 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Postagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("subtitulo", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("texto", models.TextField()),
                ("data", models.DateField()),
                ("data_criacao", models.DateField(auto_now_add=True)),
                ("data_ultima_alteracao", models.DateField(auto_now=True)),
                ("nota", models.FloatField()),
                ("qtd_likes", models.IntegerField()),
                ("status", models.BooleanField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
